name: flutter_project_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  provider: ^6.1.2
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Charis
      fonts:
        - asset: assets/fonts/CharisSIL-Bold.ttf
    - family: Scope
      fonts:
        - asset: assets/fonts/ScopeOne-Regular.ttf
